import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { DM_Sans } from "next/font/google";
import CustomToaster from "@/common/components/common/CustomToast";
import Providers from "./provider";
import SessionProvider from "@/components/providers/SessionProvider";

const dmSans = DM_Sans({
    subsets: ["latin"], // choose subsets you need
    weight: ["400", "700"], // optional: define weights you want
    variable: "--font-dm-sans", // optional CSS variable name
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "CRRSA Portal",
    description: "Generated by CRRSA.",
    keywords: "crrsa",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const locale = await getLocale();

    return (
        <html lang={locale}>
            <body className={dmSans.className}>
                <CustomToaster />
                {/* <Toaster/> */}
                <SessionProvider>
                    <NextIntlClientProvider>
                        <Providers>
                            <div className='min-h-screen'>{children}</div>
                        </Providers>
                    </NextIntlClientProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
