import { FormConfig } from "@/common/types/formType";

export const birthCorrectionFormConfig: FormConfig = {
  title: "Birth Certificate Correction",
  description: "Correct information on your birth certificate",
  stepperData: [],
  stepperPosition: "",
  grouping: {
    defaultGroup: "Correction Details",
    groups: [
      {
        name: "Correction Details",
        label: "Correction Details",
        order: 1,
      },
      {
        name: "Basic Information",
        label: "Basic Information",
        order: 2,
      },
      {
        name: "Birth Information",
        label: "Birth Information",
        order: 3,
      },
      {
        name: "Parent Information",
        label: "Parent Information",
        order: 4,
      },
      {
        name: "Identification & Personal Details",
        label: "Identification & Personal Details",
        order: 5,
      },
    ],
  },
  steps: [
    {
      title: "Basic Information",
      group: "Basic Information",
      groupOrder: 1,
      tabular: true,
      defaultExpanded: true,
      fields: [
        {
          type: "input",
          key: "childFirstName",
          label: "Child's First Name",
          placeholder: "Enter child's first name",
          validators: [
            { type: "required", message: "Child's first name is required" },
          ],
          required: true,
          group: "Basic Information",
          groupOrder: 1,
          gridCols: 6,
        },
        {
          type: "input",
          key: "childMiddleName",
          label: "Child's Middle Name",
          placeholder: "Enter child's middle name",
          validators: [],
          required: false,
          group: "Basic Information",
          groupOrder: 2,
          gridCols: 6,
        },
        {
          type: "input",
          key: "childLastName",
          label: "Child's Last Name",
          placeholder: "Enter child's last name",
          validators: [
            { type: "required", message: "Child's last name is required" },
          ],
          required: true,
          group: "Basic Information",
          groupOrder: 3,
          gridCols: 6,
        },
        {
          type: "radio",
          key: "gender",
          label: "Gender",
          options: [
            { label: "Male", value: "Male" },
            { label: "Female", value: "Female" },
          ],
          placeholder: "",
          validators: [{ type: "required", message: "Gender is required" }],
          required: true,
          group: "Basic Information",
          groupOrder: 4,
          gridCols: 6,
        },
        {
          type: "date",
          key: "birthDate",
          label: "Date of Birth",
          placeholder: "DD/MM/YYYY",
          validators: [
            { type: "required", message: "Date of birth is required" },
            {
              type: "maxDate",
              value: new Date().toISOString().split("T")[0],
              message: "Date cannot be in the future",
            },
          ],
          required: true,
          group: "Basic Information",
          groupOrder: 5,
          gridCols: 6,
        },
        {
          type: "input",
          key: "phoneNumber",
          label: "Phone Number",
          placeholder: "Enter phone number",
          validators: [
            { type: "required", message: "Phone number is required" },
            { type: "pattern", value: "^[0-9+\\-\\s()]+$", message: "Please enter a valid phone number" },
          ],
          required: true,
          group: "Basic Information",
          groupOrder: 6,
          gridCols: 6,
        },
      ],
    },
    {
      title: "Birth Information",
      group: "Birth Information",
      groupOrder: 2,
      tabular: true,
      defaultExpanded: false,
      fields: [
        {
          type: "select",
          key: "birthType",
          label: "Birth Type",
          placeholder: "Select birth type",
          options: [
            { label: "Single", value: "SINGLE" },
            { label: "Twin", value: "TWIN" },
            { label: "Triplet", value: "TRIPLET" },
            { label: "Multiple", value: "MULTIPLE" },
          ],
          validators: [
            { type: "required", message: "Birth type is required" },
          ],
          required: true,
          group: "Birth Information",
          groupOrder: 1,
          gridCols: 6,
        },
        {
          type: "number",
          key: "childWeight",
          label: "Birth Weight (kg)",
          placeholder: "Enter birth weight",
          validators: [
            { type: "required", message: "Birth weight is required" },
            { type: "min", value: 0.5, message: "Weight must be at least 0.5 kg" },
            { type: "max", value: 10, message: "Weight must be less than 10 kg" },
          ],
          required: true,
          group: "Birth Information",
          groupOrder: 2,
          gridCols: 6,
        },
        {
          type: "number",
          key: "childHeight",
          label: "Birth Height (cm)",
          placeholder: "Enter birth height",
          validators: [
            { type: "required", message: "Birth height is required" },
            { type: "min", value: 20, message: "Height must be at least 20 cm" },
            { type: "max", value: 80, message: "Height must be less than 80 cm" },
          ],
          required: true,
          group: "Birth Information",
          groupOrder: 3,
          gridCols: 6,
        },
        {
          type: "select",
          key: "placeOfBirthType",
          label: "Place of Birth Type",
          placeholder: "Select place type",
          options: [
            { label: "Health Facility", value: "HEALTH_FACILITY" },
            { label: "Home", value: "HOME" },
            { label: "Other", value: "OTHER" },
          ],
          validators: [
            { type: "required", message: "Place of birth type is required" },
          ],
          required: true,
          group: "Birth Information",
          groupOrder: 4,
          gridCols: 6,
        },
        {
          type: "input",
          key: "facilityName",
          label: "Facility Name",
          placeholder: "Enter facility name",
          validators: [
            { type: "required", message: "Facility name is required" },
          ],
          required: true,
          group: "Birth Information",
          groupOrder: 5,
          gridCols: 6,
        },
        {
          type: "input",
          key: "attendantName",
          label: "Attendant Name",
          placeholder: "Enter attendant name",
          validators: [
            { type: "required", message: "Attendant name is required" },
          ],
          required: true,
          group: "Birth Information",
          groupOrder: 6,
          gridCols: 6,
        },
        {
          type: "input",
          key: "attendantQualification",
          label: "Attendant Qualification",
          placeholder: "Enter attendant qualification",
          validators: [
            { type: "required", message: "Attendant qualification is required" },
          ],
          required: true,
          group: "Birth Information",
          groupOrder: 7,
          gridCols: 6,
        },
        {
          type: "select",
          key: "countryOfBirth",
          label: "Country of Birth",
          placeholder: "Select country of birth",
          options: [
            { label: "Ethiopia", value: "Ethiopia" },
            { label: "Kenya", value: "Kenya" },
            { label: "Sudan", value: "Sudan" },
            { label: "Somalia", value: "Somalia" },
            { label: "Djibouti", value: "Djibouti" },
            { label: "Eritrea", value: "Eritrea" },
            { label: "Other", value: "Other" },
          ],
          validators: [
            { type: "required", message: "Country of birth is required" },
          ],
          required: true,
          group: "Birth Information",
          groupOrder: 8,
          gridCols: 6,
        },
        {
          type: "select",
          key: "region",
          label: "Region",
          placeholder: "Select region",
          options: [
            { label: "Addis Ababa", value: "Addis Ababa" },
            { label: "Oromia", value: "Oromia" },
            { label: "Amhara", value: "Amhara" },
            { label: "Tigray", value: "Tigray" },
            { label: "SNNPR", value: "SNNPR" },
            { label: "Afar", value: "Afar" },
            { label: "Harari", value: "Harari" },
            { label: "Dire Dawa", value: "Dire Dawa" },
            { label: "Gambela", value: "Gambela" },
            { label: "Somali", value: "Somali" },
            { label: "Benishangul-Gumuz", value: "Benishangul-Gumuz" },
            { label: "Other", value: "Other" },
          ],
          validators: [
            { type: "required", message: "Region is required" },
          ],
          required: true,
          group: "Birth Information",
          groupOrder: 9,
          gridCols: 6,
        },
        {
          type: "select",
          key: "zoneSubcity",
          label: "Zone/Subcity",
          placeholder: "Select zone/subcity",
          options: [
            { label: "Addis Ababa", value: "Addis Ababa" },
            { label: "Bole", value: "Bole" },
            { label: "Nifas Silk-Lafto", value: "Nifas Silk-Lafto" },
            { label: "Kolfe Keranio", value: "Kolfe Keranio" },
            { label: "Gullele", value: "Gullele" },
            { label: "Lideta", value: "Lideta" },
            { label: "Kirkos", value: "Kirkos" },
            { label: "Arada", value: "Arada" },
            { label: "Addis Ketema", value: "Addis Ketema" },
            { label: "Yeka", value: "Yeka" },
            { label: "Other", value: "Other" },
          ],
          validators: [
            { type: "required", message: "Zone/Subcity is required" },
          ],
          required: true,
          group: "Birth Information",
          groupOrder: 10,
          gridCols: 6,
        },
        {
          type: "select",
          key: "woreda",
          label: "Woreda",
          placeholder: "Select woreda",
          options: [
            { label: "Bole", value: "Bole" },
            { label: "Nifas Silk-Lafto", value: "Nifas Silk-Lafto" },
            { label: "Kolfe Keranio", value: "Kolfe Keranio" },
            { label: "Gullele", value: "Gullele" },
            { label: "Lideta", value: "Lideta" },
            { label: "Kirkos", value: "Kirkos" },
            { label: "Arada", value: "Arada" },
            { label: "Addis Ketema", value: "Addis Ketema" },
            { label: "Yeka", value: "Yeka" },
            { label: "Other", value: "Other" },
          ],
          validators: [
            { type: "required", message: "Woreda is required" },
          ],
          required: true,
          group: "Birth Information",
          groupOrder: 11,
          gridCols: 6,
        },
        {
          type: "select",
          key: "kebele",
          label: "Kebele",
          placeholder: "Select kebele",
          options: [
            { label: "Kebele 01", value: "Kebele 01" },
            { label: "Kebele 02", value: "Kebele 02" },
            { label: "Kebele 03", value: "Kebele 03" },
            { label: "Kebele 04", value: "Kebele 04" },
            { label: "Kebele 05", value: "Kebele 05" },
            { label: "Kebele 06", value: "Kebele 06" },
            { label: "Kebele 07", value: "Kebele 07" },
            { label: "Kebele 08", value: "Kebele 08" },
            { label: "Kebele 09", value: "Kebele 09" },
            { label: "Kebele 10", value: "Kebele 10" },
            { label: "Other", value: "Other" },
          ],
          validators: [
            { type: "required", message: "Kebele is required" },
          ],
          required: true,
          group: "Birth Information",
          groupOrder: 12,
          gridCols: 6,
        },
      ],
    },
    {
      title: "Parent Information",
      group: "Parent Information",
      groupOrder: 3,
      tabular: true,
      defaultExpanded: false,
      fields: [
        {
          type: "input",
          key: "fatherFirstName",
          label: "Father's First Name",
          placeholder: "Enter father's first name",
          validators: [
            { type: "required", message: "Father's first name is required" },
          ],
          required: true,
          group: "Parent Information",
          groupOrder: 1,
          gridCols: 6,
        },
        {
          type: "input",
          key: "fatherLastName",
          label: "Father's Last Name",
          placeholder: "Enter father's last name",
          validators: [
            { type: "required", message: "Father's last name is required" },
          ],
          required: true,
          group: "Parent Information",
          groupOrder: 2,
          gridCols: 6,
        },
        {
          type: "input",
          key: "motherFirstName",
          label: "Mother's First Name",
          placeholder: "Enter mother's first name",
          validators: [
            { type: "required", message: "Mother's first name is required" },
          ],
          required: true,
          group: "Parent Information",
          groupOrder: 3,
          gridCols: 6,
        },
        {
          type: "input",
          key: "motherLastName",
          label: "Mother's Last Name",
          placeholder: "Enter mother's last name",
          validators: [
            { type: "required", message: "Mother's last name is required" },
          ],
          required: true,
          group: "Parent Information",
          groupOrder: 4,
          gridCols: 6,
        },
        {
          type: "lookup",
          key: "fatherNationality",
          label: "Father's Nationality",
          placeholder: "Select father's nationality",
          validators: [
            { type: "required", message: "Father's nationality is required" },
          ],
          required: true,
          group: "Parent Information",
          groupOrder: 5,
          gridCols: 6,
          lookupConfig: {
            apiEndpoint: "/reference-data/nationalities",
            method: "GET",
            valueKey: "id",
            labelKey: "name",
            searchKey: "name",
            debounceMs: 300,
            minSearchLength: 0,
            cacheResults: true,
            transformResponse: (response, locale: "en" | "am" = "en") => {
              if (!response?.content) {
                return [];
              }

              const transformedData = response.content.map((res: any) => ({
                id: res.id,
                value: res.id,
                name: res.localizedContent?.[locale]?.name ?? res.code,
                label: res.localizedContent?.[locale]?.name ?? res.code,
                isDisabled: false,
                code: res.code,
              }));

              return transformedData;
            },
          },
        },
        {
          type: "lookup",
          key: "motherNationality",
          label: "Mother's Nationality",
          placeholder: "Select mother's nationality",
          validators: [
            { type: "required", message: "Mother's nationality is required" },
          ],
          required: true,
          group: "Parent Information",
          groupOrder: 6,
          gridCols: 6,
          lookupConfig: {
            apiEndpoint: "/reference-data/nationalities",
            method: "GET",
            valueKey: "id",
            labelKey: "name",
            searchKey: "name",
            debounceMs: 300,
            minSearchLength: 0,
            cacheResults: true,
            transformResponse: (response, locale: "en" | "am" = "en") => {
              if (!response?.content) {
                return [];
              }

              const transformedData = response.content.map((res: any) => ({
                id: res.id,
                value: res.id,
                name: res.localizedContent?.[locale]?.name ?? res.code,
                label: res.localizedContent?.[locale]?.name ?? res.code,
                isDisabled: false,
                code: res.code,
              }));

              return transformedData;
            },
          },
        },
      ],
    },
    {
      title: "Identification & Personal Details",
      group: "Identification & Personal Details",
      groupOrder: 4,
      tabular: true,
      defaultExpanded: false,
      fields: [
        {
          type: "input",
          key: "passportNo",
          label: "Passport No",
          placeholder: "Enter passport number",
          validators: [],
          required: false,
          group: "Identification & Personal Details",
          groupOrder: 1,
          gridCols: 6,
        },
        {
          type: "input",
          key: "fin",
          label: "FIN",
          placeholder: "Enter FIN number",
          validators: [],
          required: false,
          group: "Identification & Personal Details",
          groupOrder: 2,
          gridCols: 6,
        },
        {
          type: "input",
          key: "driversLicenseNo",
          label: "Drivers License No",
          placeholder: "Enter drivers license number",
          validators: [],
          required: false,
          group: "Identification & Personal Details",
          groupOrder: 3,
          gridCols: 6,
        },
        {
          type: "select",
          key: "maritalStatus",
          label: "Marital Status",
          placeholder: "Select marital status",
          options: [
            { label: "Single", value: "SINGLE" },
            { label: "Married", value: "MARRIED" },
            { label: "Divorced", value: "DIVORCED" },
            { label: "Widowed", value: "WIDOWED" },
            { label: "Separated", value: "SEPARATED" },
          ],
          validators: [],
          required: false,
          group: "Identification & Personal Details",
          groupOrder: 4,
          gridCols: 6,
        },
        {
          type: "select",
          key: "educationLevel",
          label: "Education Level",
          placeholder: "Select education level",
          options: [
            { label: "No Formal Education", value: "NO_FORMAL_EDUCATION" },
            { label: "Primary", value: "PRIMARY" },
            { label: "Secondary", value: "SECONDARY" },
            { label: "High School", value: "HIGH_SCHOOL" },
            { label: "Diploma", value: "DIPLOMA" },
            { label: "Bachelor's Degree", value: "BACHELORS" },
            { label: "Master's Degree", value: "MASTERS" },
            { label: "PhD", value: "PHD" },
            { label: "Other", value: "OTHER" },
          ],
          validators: [],
          required: false,
          group: "Identification & Personal Details",
          groupOrder: 5,
          gridCols: 6,
        },
        {
          type: "select",
          key: "occupationType",
          label: "Occupation Type",
          placeholder: "Select occupation type",
          options: [
            { label: "Student", value: "STUDENT" },
            { label: "Employee", value: "EMPLOYEE" },
            { label: "Self-Employed", value: "SELF_EMPLOYED" },
            { label: "Unemployed", value: "UNEMPLOYED" },
            { label: "Retired", value: "RETIRED" },
            { label: "Homemaker", value: "HOMEMAKER" },
            { label: "Other", value: "OTHER" },
          ],
          validators: [],
          required: false,
          group: "Identification & Personal Details",
          groupOrder: 6,
          gridCols: 6,
        },
        {
          type: "input",
          key: "workPlaceName",
          label: "Work Place Name",
          placeholder: "Enter workplace name",
          validators: [],
          required: false,
          group: "Identification & Personal Details",
          groupOrder: 7,
          gridCols: 6,
        },
      ],
    },
  ],
};
